#include "neural_net_evaluator.h"

#include <gtest/gtest.h>
#include <torch/torch.h>

// ---------------------------------------------------------------------------
// Helper: fast-forward to standard phase so stone_to_place() is meaningful.
// After kSwap2ChooseBlack: A=White, B=Black, next to move is A (White).
// ---------------------------------------------------------------------------
static Board MakeStandardBoard() {
  Board b;
  b.Apply(Action::FromXY(0, 0).id);
  b.Apply(Action::FromXY(1, 0).id);
  b.Apply(Action::FromXY(2, 0).id);
  b.Apply(Action::kSwap2ChooseBlack);
  return b;
}

// ===========================================================================
// BoardToTensor encoding tests — no model or executor required
// ===========================================================================

TEST(NeuralNetEvaluatorTest, TensorShape) {
  auto t = neural_net_evaluator_internal::BoardToTensor(MakeStandardBoard());
  ASSERT_EQ(t.dim(), 3);
  EXPECT_EQ(t.size(0), NeuralNetEvaluator::kNumInputChannels);
  EXPECT_EQ(t.size(1), Board::kSize);
  EXPECT_EQ(t.size(2), Board::kSize);
}

TEST(NeuralNetEvaluatorTest, CurrentPlayerStonesInChannel0) {
  Board b = MakeStandardBoard();
  ASSERT_EQ(b.stone_to_place(), Player::kWhite);

  auto t = neural_net_evaluator_internal::BoardToTensor(b);
  auto acc = t.accessor<float, 3>();
  EXPECT_FLOAT_EQ(acc[0][0][1], 1.0f);  // (x=1, y=0) White → ch0
  EXPECT_FLOAT_EQ(acc[0][0][0], 0.0f);  // (x=0, y=0) Black → not ch0
  EXPECT_FLOAT_EQ(acc[0][0][2], 0.0f);  // (x=2, y=0) Black → not ch0
}

TEST(NeuralNetEvaluatorTest, OpponentStonesInChannel1) {
  Board b = MakeStandardBoard();
  ASSERT_EQ(b.stone_to_place(), Player::kWhite);

  auto t = neural_net_evaluator_internal::BoardToTensor(b);
  auto acc = t.accessor<float, 3>();
  EXPECT_FLOAT_EQ(acc[1][0][0], 1.0f);  // Black → ch1
  EXPECT_FLOAT_EQ(acc[1][0][2], 1.0f);  // Black → ch1
  EXPECT_FLOAT_EQ(acc[1][0][1], 0.0f);  // White → not ch1
}

TEST(NeuralNetEvaluatorTest, ColorPlanesWhiteTurn) {
  Board b = MakeStandardBoard();
  ASSERT_EQ(b.stone_to_place(), Player::kWhite);

  auto t = neural_net_evaluator_internal::BoardToTensor(b);
  auto acc = t.accessor<float, 3>();
  for (int y = 0; y < Board::kSize; ++y)
    for (int x = 0; x < Board::kSize; ++x) {
      EXPECT_FLOAT_EQ(acc[2][y][x], 0.0f);  // not Black
      EXPECT_FLOAT_EQ(acc[3][y][x], 1.0f);  // White
    }
}

TEST(NeuralNetEvaluatorTest, ColorPlanesBlackTurn) {
  Board b = MakeStandardBoard();
  b.Apply(Action::FromXY(7, 7).id);
  ASSERT_EQ(b.stone_to_place(), Player::kBlack);

  auto t = neural_net_evaluator_internal::BoardToTensor(b);
  auto acc = t.accessor<float, 3>();
  for (int y = 0; y < Board::kSize; ++y)
    for (int x = 0; x < Board::kSize; ++x) {
      EXPECT_FLOAT_EQ(acc[2][y][x], 1.0f);  // Black
      EXPECT_FLOAT_EQ(acc[3][y][x], 0.0f);  // not White
    }
}

TEST(NeuralNetEvaluatorTest, EmptyBoardChannels0And1AllZero) {
  auto t = neural_net_evaluator_internal::BoardToTensor(Board{});
  auto acc = t.accessor<float, 3>();
  for (int y = 0; y < Board::kSize; ++y)
    for (int x = 0; x < Board::kSize; ++x) {
      EXPECT_FLOAT_EQ(acc[0][y][x], 0.0f);
      EXPECT_FLOAT_EQ(acc[1][y][x], 0.0f);
    }
}

// ===========================================================================
// End-to-end inference test — requires model.pt (generated by
// python/create_initial_model.py). Skipped if the file is not present.
// ===========================================================================

TEST(NeuralNetEvaluatorTest, EndToEndWithRealModel) {
  const std::filesystem::path model_path = "model.pt";
  if (!std::filesystem::exists(model_path)) {
    GTEST_SKIP()
        << "model.pt not found; run: cd python && python create_model.py";
  }

  torch::Device device =
      torch::cuda::is_available() ? torch::kCUDA : torch::kCPU;
  auto exec = std::make_shared<BatchInferenceExecutor>(
      model_path, device, /*max_batch_size=*/8,
      /*max_wait_us=*/std::chrono::microseconds(500));
  NeuralNetEvaluator evaluator(exec);

  Board b = MakeStandardBoard();
  EvaluationResult r = evaluator.Evaluate(b);

  ASSERT_EQ(static_cast<int>(r.move_pmf.size()), Board::kNumActions);
  float sum = 0.0f;
  for (float p : r.move_pmf) {
    EXPECT_GE(p, 0.0f);
    sum += p;
  }
  EXPECT_NEAR(sum, 1.0f, 1e-4f);
  EXPECT_GE(r.value, -1.0f);
  EXPECT_LE(r.value, 1.0f);
}
